version: '3.0'

services:
  api:
    container_name: docker-test-api
    build: .
    volumes:
      - type: bind
        source: ./app
        target: /app
    expose:
      - 8000
    ports:
      - '8000:8000'
